apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: jy2545acr.azurecr.io/frontend-react
    newTag: main-20240820131120

commonLabels:
  app: frontend-react
  environment: dev
