version: '3'
name: 'nginx_react_typescript_docker'

services:
  app:
    image: front-react
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./nginx/nginx.conf://etc/nginx/nginx.conf:ro"
    networks:
      network:
         ipv4_address: 172.0.0.2

networks:
  network:
    driver: bridge
    ipam:
      config:
          - subnet: 172.0.0.0/16
            gateway: 172.0.0.1